AnimationIdlePointers:
	table_width 2
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw WeedleAnimationIdle
	dw KakunaAnimationIdle
	dw BeedrillAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw SpearowAnimationIdle
	dw FearowAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw SandshrewAnimationIdle
	dw SandslashAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw OddishAnimationIdle
	dw GloomAnimationIdle
	dw VileplumeAnimationIdle
	dw ParasAnimationIdle
	dw ParasectAnimationIdle
	dw VenonatAnimationIdle
	dw VenomothAnimationIdle
	dw DiglettAnimationIdle
	dw DugtrioAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw FarfetchDAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw KrabbyAnimationIdle
	dw KinglerAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw MunchlaxAnimationIdle
	dw TreeckoAnimationIdle
	dw GrovyleAnimationIdle
	dw SceptileAnimationIdle
	dw TorchicAnimationIdle
	dw CombuskenAnimationIdle
	dw BlazikenAnimationIdle
	dw MudkipAnimationIdle
	dw MarshtompAnimationIdle
	dw SwampertAnimationIdle
	dw PoochyenaAnimationIdle
	dw MightyenaAnimationIdle
	dw ZigzagoonAnimationIdle
	dw LinooneAnimationIdle
	dw WurmpleAnimationIdle
	dw SilcoonAnimationIdle
	dw BeautiflyAnimationIdle
	dw CascoonAnimationIdle
	dw DustoxAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw SeedotAnimationIdle
	dw NuzleafAnimationIdle
	dw ShiftryAnimationIdle
	dw TaillowAnimationIdle
	dw SwellowAnimationIdle
	dw WingullAnimationIdle
	dw PelipperAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw SurskitAnimationIdle
	dw MasquerainAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw SlakothAnimationIdle
	dw VigorothAnimationIdle
	dw SlakingAnimationIdle
	dw NincadaAnimationIdle
	dw NinjaskAnimationIdle
	dw ShedinjaAnimationIdle
	dw WhismurAnimationIdle
	dw LoudredAnimationIdle
	dw ExploudAnimationIdle
	dw MakuhitaAnimationIdle
	dw HariyamaAnimationIdle
	dw AzurillAnimationIdle
	dw NosepassAnimationIdle
	dw SkittyAnimationIdle
	dw DelcattyAnimationIdle
	dw SableyeAnimationIdle
	dw MawileAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw MedititeAnimationIdle
	dw MedichamAnimationIdle
	dw ElectrikeAnimationIdle
	dw ManectricAnimationIdle
	dw PlusleAnimationIdle
	dw MinunAnimationIdle
	dw VolbeatAnimationIdle
	dw IllumiseAnimationIdle
	dw RoseliaAnimationIdle
	dw GulpinAnimationIdle
	dw SwalotAnimationIdle
	dw CarvanhaAnimationIdle
	dw SharpedoAnimationIdle
	dw WailmerAnimationIdle
	dw WailordAnimationIdle
	dw NumelAnimationIdle
	dw CameruptAnimationIdle
	dw TorkoalAnimationIdle
	dw SpoinkAnimationIdle
	dw GrumpigAnimationIdle
	dw SpindaAnimationIdle
	dw TrapinchAnimationIdle
	dw VibravaAnimationIdle
	dw FlygonAnimationIdle
	dw CacneaAnimationIdle
	dw CacturneAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw ZangooseAnimationIdle
	dw SeviperAnimationIdle
	dw LunatoneAnimationIdle
	dw SolrockAnimationIdle
	dw BarboachAnimationIdle
	dw WhiscashAnimationIdle
	dw CorphishAnimationIdle
	dw CrawdauntAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw LileepAnimationIdle
	dw CradilyAnimationIdle
	dw AnorithAnimationIdle
	dw ArmaldoAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw KecleonAnimationIdle
	dw ShuppetAnimationIdle
	dw BanetteAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw TropiusAnimationIdle
	dw ChimechoAnimationIdle
	dw AbsolAnimationIdle
	dw WynautAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw SphealAnimationIdle
	dw SealeoAnimationIdle
	dw WalreinAnimationIdle
	dw ClamperlAnimationIdle
	dw HuntailAnimationIdle
	dw GorebyssAnimationIdle
	dw RelicanthAnimationIdle
	dw LuvdiscAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw RegirockAnimationIdle
	dw RegiceAnimationIdle
	dw RegisteelAnimationIdle
	dw LatiasAnimationIdle
	dw LatiosAnimationIdle
	dw KyogreAnimationIdle
	dw GroudonAnimationIdle
	dw RayquazaAnimationIdle
	dw JirachiAnimationIdle
	;Gen4
	dw TogekissAnimationIdle
	dw MamoswineAnimationIdle
	dw SylveonAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw GliscorAnimationIdle
	dw GalladeAnimationIdle
	dw FroslassAnimationIdle
	dw HonchkrowAnimationIdle
	dw WeavileAnimationIdle
	dw MagnezoneAnimationIdle
	dw TangrowthAnimationIdle
	dw ElectivireAnimationIdle
	dw MagmortarAnimationIdle
	dw WyrdeerAnimationIdle
	dw PorygonzAnimationIdle
	dw AnnihilapeAnimationIdle
	dw KleavorAnimationIdle
	dw RoseradeAnimationIdle
	dw AmbipomAnimationIdle
	dw MismagiusAnimationIdle
	dw LickilickyAnimationIdle
	dw RhyperiorAnimationIdle
	dw YanmegaAnimationIdle
	dw ProbopassAnimationIdle
	dw DusknoirAnimationIdle
	;alt forms
	dw AraichuAnimationIdle
	dw AmarowakAnimationIdle
	dw AgrimerAnimationIdle
	dw AmukAnimationIdle
	dw AsandshrewAnimationIdle
	dw AsandslashAnimationIdle
	dw AvulpixAnimationIdle
	dw AninetalesAnimationIdle
	dw AgeodudeAnimationIdle
	dw AgravelerAnimationIdle
	dw AgolemAnimationIdle
	dw HvoltorbAnimationIdle
	dw HelectrodeAnimationIdle
	dw IronbundleAnimationIdle
	;reddit mons
	dw Voltorb2AnimationIdle
	dw Electrode2AnimationIdle
	dw Exeggcute2AnimationIdle
	dw Exeggutor2AnimationIdle
	dw Furret2AnimationIdle
	dw Noctowl2AnimationIdle
	dw Octillery2AnimationIdle
	dw Yanma2AnimationIdle
	dw Scyther2AnimationIdle
	dw Scizor2AnimationIdle
	dw Tentacool2AnimationIdle
	dw Tentacruel2AnimationIdle
	dw Rapidash2AnimationIdle
	dw Ninetales2AnimationIdle
	dw Tauros2AnimationIdle
	dw Swinub2AnimationIdle
	dw Piloswine2AnimationIdle
	dw Skarmory2AnimationIdle
	dw Totodile2AnimationIdle
	dw Croconaw2AnimationIdle
	dw Feraligatr2AnimationIdle
	dw Cyndaquil2AnimationIdle
	dw Quilava2AnimationIdle
	dw Typhlosion2AnimationIdle
	;beta mons
	dw HanamoleAnimationIdle
	dw HonobeaAnimationIdle
	dw BorubeaAnimationIdle
	dw DynabeaAnimationIdle
	dw KurusuAnimationIdle
	dw AkuaAnimationIdle
	dw AkueriaAnimationIdle
	dw HaneeiAnimationIdle
	dw TsubomittAnimationIdle
	dw KotoraAnimationIdle
	dw RaitoraAnimationIdle
	dw AshibombAnimationIdle
	dw SunbouAnimationIdle
	dw IkariAnimationIdle
	dw TotartleAnimationIdle
	dw GorochuAnimationIdle
	;mega
	dw RaichuxAnimationIdle
	dw RaichuyAnimationIdle
	dw DragonitexAnimationIdle
	dw DragoniteyAnimationIdle
	dw VenusaurxAnimationIdle
	dw CharizardxAnimationIdle
	dw CharizardyAnimationIdle
	dw BlastoisexAnimationIdle
	dw BeedrillxAnimationIdle
	dw AlakazamxAnimationIdle
	dw SlowbroxAnimationIdle
	dw GengarxAnimationIdle
	dw PinsirxAnimationIdle
	dw GyaradosxAnimationIdle
	dw AerodactylxAnimationIdle
	dw AmpharosxAnimationIdle
	dw SteelixxAnimationIdle
	dw ScizorxAnimationIdle
	dw HeracrossxAnimationIdle
	dw HoundoomxAnimationIdle
	dw TyranitarxAnimationIdle
	dw AggronxAnimationIdle
	dw CameruptxAnimationIdle
	dw AltariaxAnimationIdle
	dw AbsolxAnimationIdle
	dw GlaliexAnimationIdle
	dw SalamencexAnimationIdle
	dw MetagrossxAnimationIdle
	dw KinglerxAnimationIdle
	dw TropiusxAnimationIdle
	dw SwalotxAnimationIdle
	dw FlygonxAnimationIdle
	dw ChimechoxAnimationIdle
	dw VictreebelxAnimationIdle
	assert_table_length NUM_POKEMON
